#Don't change this
[config]
  schemaVersion="0.0.1"

[package]
  #Edit these in Directory.Build.props instead, the workflow will automate copying
  #it here for you
  description="Configure gift boxes / presents, such as having store items / scrap / another present / nothing, weighting of item selection, spawn rates, etc."

  #Change this to true if your mod has any NSFW content. Please follow the rules
  #on image and text content on your listing or your package may be removed
  containsNsfwContent=false

  #This is the link that shows up in the top right of the package page
  #while it can be anything, I suggest keeping it as your github
  websiteUrl="https://github.com/DecibillyJoel/LC_GiftBox_Config"

  #This is where you put in dependencies in the format
  #DependencyNamespace-ModName = "version.number.here"
  [package.dependencies]
    BepInEx-BepInExPack="5.4.2100"
    xilophor-StaticNetcodeLib="1.1.1"
    Evaisa-FixPluginTypesSerialization="1.1.2"
    DBJ-ILUtils="1.0.4"
    DBJ-LCUtils="1.0.6"

#These settings will import the repo's README.md file and the icon in the
#same folder as this TOML file as your icon. Please replace the icon with
#something prettier! You do not need to modify these settings!
[build]
  icon  ="./../../docs/icon.png"
  outdir="./../../artifacts/tspublish/build"
  readme="./../../docs/README.md"

  [[build.copy]]
    source="./../../artifacts/tspublish/dist"
    target="./"

#Don't change this
[general]
  repository="https://thunderstore.io"

#Don't change this
[publish]
  communities=["lethal-company"]
  repository ="https://thunderstore.io"

  #There is a list of tags in the tutorial
  [publish.categories]
    lethal-company=["mods", "items", "serverside", "tweaks-and-quality-of-life"]
